#!/bin/sh
##############################
#
#  Script to install basic files needed for git
#
##############################

echo "----------------  INSTALLING GIT-CORE"
apt-get --force-yes install git-core

echo "----------------  INSTALLING G++"
apt-get --force-yes install g++

echo "-----------------  INSTALLING BUILD_ESSENTIAL"
apt-get --force-yes install build-essential

echo "-----------------  INSTALLING LIBSSL-DEV"
apt-get --force-yes install libssl-dev

chmod +x DevelopmentInstall.sh
